import { GENERATED_PERMISSION_NIDS } from './catalog.generated'

/**
 * 前端权限目录(与后端 PermissionCatalog 对齐,§9.2/§29A.5)。
 * 路由 meta、导航菜单与 PermissionGate 一律引用常量,避免字符串漂移。
 */

export const PERMISSIONS = {
  userView: 'identity.user.view',
  userCreate: 'identity.user.create',
  userUpdate: 'identity.user.update',
  userStatus: 'identity.user.status',
  userAssignRole: 'identity.user.assign-role',
  userDelete: 'identity.user.delete',
  userRestore: 'identity.user.restore',
  roleView: 'identity.role.view',
  roleCreate: 'identity.role.create',
  roleUpdate: 'identity.role.update',
  roleAssignPermission: 'identity.role.assign-permission',
  userGroupDelete: 'identity.user-group.delete',
  userGroupRestore: 'identity.user-group.restore',
  userGroupView: 'identity.user-group.view',
  userGroupCreate: 'identity.user-group.create',
  userGroupUpdate: 'identity.user-group.update',
  userGroupStatus: 'identity.user-group.status',
  userGroupAssignMember: 'identity.user-group.assign-member',
  userGroupAssignRole: 'identity.user-group.assign-role',
  userResetPassword: 'identity.user.reset-password',
  permissionView: 'identity.permission.view',
  auditLoginView: 'identity.audit.login.view',
  ssoView: 'identity.sso.view',
  ssoManage: 'identity.sso.manage',
  ssoTest: 'identity.sso.test',
  sessionView: 'identity.session.view',
  sessionRevoke: 'identity.session.revoke',
  platformHomeView: 'platform.home.view',
  platformOperationView: 'platform.operation.view',
  platformPdaView: 'platform.pda.view',
  platformMobileView: 'platform.mobile.view',
  bootstrapView: 'identity.bootstrap.view',
  bootstrapRecover: 'identity.bootstrap.recover',
  systemDataOrganizationView: 'systemdata.organization.view',
  systemDataOrganizationCreate: 'systemdata.organization.create',
  systemDataOrganizationUpdate: 'systemdata.organization.update',
  systemDataOrganizationMove: 'systemdata.organization.move',
  systemDataOrganizationStatus: 'systemdata.organization.status',
  systemDataPositionView: 'systemdata.position.view',
  systemDataPositionCreate: 'systemdata.position.create',
  systemDataPositionUpdate: 'systemdata.position.update',
  systemDataPositionStatus: 'systemdata.position.status',
  systemDataAssignmentView: 'systemdata.assignment.view',
  systemDataAssignmentManage: 'systemdata.assignment.manage',
  systemDataResourceView: 'systemdata.resource.view',
  systemDataNavigationView: 'systemdata.navigation.view',
  systemDataNavigationManage: 'systemdata.navigation.manage',
  systemDataNavigationPublish: 'systemdata.navigation.publish',
  systemDataNavigationRollback: 'systemdata.navigation.rollback',
  systemDataFeatureView: 'systemdata.feature.view',
  systemDataFeatureManage: 'systemdata.feature.manage',
  systemDataServiceCatalogView: 'systemdata.service-catalog.view',
  systemDataServiceCatalogManage: 'systemdata.service-catalog.manage',
  systemDataThemePolicyView: 'systemdata.theme-policy.view',
  systemDataThemePolicyManage: 'systemdata.theme-policy.manage',
  systemDataDatabaseOrchestrationView: 'systemdata.database-orchestration.view',
  systemDataDatabaseOrchestrationRegister: 'systemdata.database-orchestration.register',
  systemDataDatabaseOrchestrationPlan: 'systemdata.database-orchestration.plan',
  systemDataDatabaseOrchestrationApply: 'systemdata.database-orchestration.apply',
  systemDataDatabaseOrchestrationApprove: 'systemdata.database-orchestration.approve',
  systemDataDatabaseOrchestrationBackup: 'systemdata.database-orchestration.backup',
  systemDataDatabaseOrchestrationCancel: 'systemdata.database-orchestration.cancel',
  systemDataServiceInitializationView: 'systemdata.service-initialization.view',
  systemDataServiceInitializationRegister: 'systemdata.service-initialization.register',
  systemDataServiceInitializationPlan: 'systemdata.service-initialization.plan',
  systemDataServiceInitializationApply: 'systemdata.service-initialization.apply',
  systemDataServiceInitializationApprove: 'systemdata.service-initialization.approve',
  systemDataServiceInitializationBackup: 'systemdata.service-initialization.backup',
  systemDataServiceInitializationCancel: 'systemdata.service-initialization.cancel',
} as const

export type PermissionNId = (typeof PERMISSIONS)[keyof typeof PERMISSIONS]

export { GENERATED_PERMISSION_NIDS }
