export const referenceDataZh = {
  section: '参考数据',
  parameterTitle: '参数管理',
  parameterDescription: '按应用域维护配置键；命中启用键后，空值也会阻断继承。',
  domains: '应用域',
  newDomain: '新建应用域',
  keys: '配置键',
  newKey: '新增配置键',
  newValue: '新增明细',
  selectDomain: '请选择一个应用域',
  domainLoading: '正在加载应用域',
  keyCount: '键数量',
  active: '生效中',
  enable: '启用',
  changeReason: '变更原因',
  parameterStateHint: '状态变化会立即影响有效配置。停用后恢复下级作用域继承。',
  dataType: '数据类型',
  valueMode: '值模式',
  singleValue: '单值',
  multiValue: '多值',
  value: '配置值',
  defaultValue: '默认值',
  notConfigured: '未配置',
  mandatory: '必填',
  readOnlyKey: '只读键',
  readOnlyHint: '此键只能由受信任同步或迁移修改。',
  typeLocked: '此路径曾有实际值，类型和模式已固定；需要变更请新增键。',
  dictionaryNId: '已发布字典标识',
  referenceTarget: '引用目标',
  fullPath: '完整路径',
  blocksInheritance: '阻断下级继承',
  emptyValueHint: '未配置值时使用默认值；两者均未配置会阻断继承。恢复继承请停用此键。',
  multiValueHint: '返回全部启用明细；默认项可多选，但必须启用。先添加明细，再将多值键设为必填。',
  isDefault: '默认项',
  history: '变更历史',
  historyBefore: '变更前摘要',
  historyAfter: '变更后摘要',
  objectType: '对象',
  changeType: '变更',
  changedBy: '操作者',
  effective: '有效配置',
  valueSource: '值来源',
  usesDefault: '使用默认值',
  configuredValue: '使用配置值',
  viewEffective: '查看有效配置',
  noKeys: '此应用域还没有配置键。',
  keyLimit: '一个应用域最多 500 个键。',
  multiLimit: '每个多值键最多 1000 条明细。',
  duplicateValue: '启用明细的值不能重复。',
  duplicateConfiguration: '业务标识已存在。',
  mandatoryMissing: '必填键需要单值、默认值，或至少一条启用明细。',
  modeConflict: '单值与多值内容不能混用。',
  defaultMustBeEnabled: '默认项必须启用；请先取消默认标记。',
  sensitiveRejected: '参数不能存储密码、令牌、私钥或含凭据的连接串。',
  jsonInvalid: '请输入合法的类型值；未配置请使用上方开关。',
  valueDetails: '多值明细',
  decimalHint: '保留原始十进制精度',
  typeString: '字符串',
  typeInteger: '整数（Int64）',
  typeDecimal: '十进制数',
  typeBoolean: '布尔值',
  typeDate: '日期',
  typeDateTime: '时间（含时区）',
  typeEnum: '字典枚举',
  typeJson: 'JSON 数据',
  typeReference: '不透明引用',
  trueValue: '是（true）',
  falseValue: '否（false）',
  noDomain: '暂无应用域，可新建第一个应用域。',
  enumLoad: '读取字典项',
  noValues: '暂无多值明细',
  parameterIdentityHint: '应用域和键标识不含点号，保存后不能改名。',
  dictionaryTitle: '字典管理',
  dictionaryDescription: '维护版本化字典。租户字典整本覆盖平台字典，发布后内容只读。',
  create: '新建字典',
  edit: '编辑',
  detail: '详情',
  clone: '克隆新版本',
  publish: '发布',
  disable: '停用',
  more: '更多',
  keyword: '关键字',
  name: '名称',
  nId: '业务标识',
  scope: '作用域',
  status: '状态',
  revision: '修订',
  enabledCount: '启用项数',
  updatedOn: '更新时间',
  publishedBy: '发布人',
  description: '说明',
  tenant: '租户',
  platform: '平台',
  all: '全部',
  draft: '草稿',
  published: '已发布',
  superseded: '已被替代',
  disabled: '已停用',
  basics: '基本信息',
  items: '字典项',
  addItem: '新增字典项',
  enabled: '启用',
  sort: '排序',
  moveUp: '上移',
  moveDown: '下移',
  remove: '移除',
  save: '保存',
  cancel: '取消',
  close: '关闭',
  refresh: '刷新',
  required: '请填写此字段',
  invalidNId: '标识格式不正确',
  duplicateItem: '字典项标识不能重复',
  invalidSort: '排序必须为非负整数',
  itemLimit: '字典最多包含 1000 项',
  enabledRequired: '发布前至少需要一个启用项',
  historyProtected: '历史项不可移除，请停用后新增其他标识。',
  readOnly: '此版本只读。需要修改时请克隆新草稿。',
  protected: '记录已冻结、锁定，或缺少此作用域的管理权限。',
  publicationTitle: '发布校验与差异',
  previousRevision: '上一已发布修订',
  firstPublication: '首次发布',
  added: '新增项',
  changed: '变更项',
  disabledItems: '停用项',
  validationPassed: '校验通过，可以发布。',
  noChanges: '无',
  publicationHint: '发布将替代同作用域的当前版本，历史内容仍保留。',
  reason: '停用原因',
  disableHint: '停用后不再作为当前有效字典；租户字典停用后将回退到平台字典。',
  conflict: '数据已变化。未保存输入已保留，请复制内容或重新加载后处理。',
  reload: '重新加载',
  copyUnsaved: '复制未保存内容',
  copied: '已复制未保存内容',
  discard: '存在未保存修改，确定放弃吗？',
  saved: '保存成功',
  publishedSuccess: '发布成功',
  disabledSuccess: '停用成功',
  cloned: '已创建新草稿',
  unavailable: '参考数据服务暂不可用，请稍后重试。',
  forbidden: '没有执行此操作的权限。',
  notFound: '记录不存在或不可访问。',
  invalid: '数据校验失败，请检查字段。',
  stateInvalid: '当前状态不允许此操作。',
  traceId: '追踪标识',
  empty: '暂无字典，可新建第一本字典。',
  loading: '正在加载字典',
  itemIdentityHint: '标识会统一为大写；已发布的字典项应停用，不应删除或重命名。',
  formTitle: '字典',
  copyFailed: '复制失败，请手动保留输入。',
  dynamicTitle: '动态属性',
  dynamicDescription: '维护版本化动态配置定义、字段和记录；租户版本整份替换平台版本。',
  dynamicCreate: '新建动态配置',
  dynamicSelect: '请选择一个动态配置定义',
  dynamicLoading: '正在加载动态配置',
  dynamicEmpty: '暂无动态配置，可新建第一个定义。',
  dynamicFields: '字段定义',
  dynamicRecords: '配置记录',
  dynamicPublication: '发布校验',
  dynamicFieldCount: '字段数',
  dynamicRecordCount: '记录数',
  dynamicValueCount: '值数量',
  publishedOn: '发布时间',
  dynamicEditDefinition: '编辑定义',
  dynamicAddField: '新增字段',
  dynamicEditField: '编辑字段',
  dynamicAddRecord: '新增记录',
  dynamicEditRecord: '编辑记录',
  dynamicPublicationCheck: '发布校验',
  dynamicDefinitionDetails: '动态配置定义',
  dynamicFieldDetails: '字段详情',
  dynamicRecordDetails: '记录详情',
  dynamicRequired: '必需字段',
  dynamicCategory: '分类',
  dynamicValues: '字段值',
  dynamicMinLength: '最小长度',
  dynamicMaxLength: '最大长度',
  dynamicMinValue: '最小值',
  dynamicMaxValue: '最大值',
  dynamicScale: '小数位',
  dynamicPattern: '正则约束',
  dynamicNoFields: '此定义还没有字段。',
  dynamicFieldIdentityHint: '字段标识在保存后不可改名；已有值或发布过的字段须保留并停用。',
  dynamicReplacementHint: '租户动态配置会整份替换平台配置，不会按记录合并。',
  dynamicRemoveFieldHint: '确定移除此尚未使用且从未发布的字段吗？',
  dynamicDisableRecordHint: '停用后记录不会出现在运行时结果中，请填写原因。',
  dynamicInvalid: '动态配置的字段定义或记录值不符合约束。',
  dynamicLimit: '动态配置已超过字段、记录或值数量限制。',
  dynamicEnumInvalid: '枚举值必须来自当前作用域的已发布字典。',
  dynamicConstraintInvalid: '约束范围不正确。',
  unitTitle: '计量单位',
  unitDescription: '维护版本化计量维度和基准换算，并按固定来源与修订进行服务端试算。',
  unitCreate: '新建计量维度',
  unitEdit: '编辑计量维度',
  unitDetail: '计量维度详情',
  unitEmpty: '暂无计量维度，可新建第一个租户维度。',
  unitConversionKind: '换算类型',
  unitRatio: '比例换算',
  unitAbsoluteTemperature: '绝对温度',
  unitBase: '基准单位',
  unitCount: '单位数',
  unitDefinitions: '单位定义',
  unitAdd: '新增单位',
  unitNoDefinitions: '请至少新增一个单位并设置基准单位。',
  unitNId: '单位标识',
  unitName: '单位名称',
  unitSymbol: '符号',
  unitFactor: '基准因子',
  unitOffset: '基准偏移',
  unitDecimalPlaces: '小数位',
  unitRoundingMode: '舍入模式',
  unitToEven: '银行家舍入',
  unitAwayFromZero: '远离零',
  unitSystemDefined: '系统预置',
  unitSystemReadOnly: '系统预置计量维度由版本化种子维护，普通管理权限下全部只读。',
  unitLimit: '每个计量维度必须包含 1～200 个单位。',
  unitDuplicate: '同一维度内单位标识不能重复。',
  unitFactorInvalid: '因子必须为大于 0 的十进制字符串。',
  unitDecimalInvalid: '请输入不含指数的十进制字符串。',
  unitRatioOffset: '比例换算的偏移必须为 0。',
  unitDecimalPlacesInvalid: '小数位必须是 0～12 的整数。',
  unitBaseInvalid: '基准单位必须存在、启用，且因子为 1、偏移为 0。',
  unitDecimalHint: '数量、因子、偏移和结果始终保留为十进制字符串。',
  unitInvalid: '计量维度、单位或换算参数不符合约束。',
  unitOverflow: '换算结果超出可表示范围。',
  unitPublishHint: '发布会原子冻结整份单位修订，并替代同一来源的当前版本。',
  unitDisableHint: '停用后不再用于新的选择；固定历史修订仍可读取和解释。',
  unitTryConvert: '试算',
  unitConvertTitle: '单位换算试算',
  unitConvert: '换算',
  unitFrom: '源单位',
  unitTo: '目标单位',
  unitReadMode: '读取方式',
  unitFixedRevision: '固定修订',
  unitCurrentRevision: '当前版本',
  unitWasRounded: '发生舍入',
  metadataTitle: '元数据 Schema',
  metadataDescription:
    '维护版本化实体 Schema 与属性约束；运行时可读取当前有效定义或显式来源的固定修订。',
  metadataCreate: '新建 Schema',
  metadataEdit: '编辑 Schema',
  metadataDetail: 'Schema 详情',
  metadataEmpty: '暂无元数据 Schema，可新建第一个租户定义。',
  metadataAttributeCount: '属性数',
  metadataAttributes: '属性定义',
  metadataAddAttribute: '新增属性',
  metadataNoAttributes: '请至少新增一个启用属性后再发布。',
  metadataAttributeIdentityHint: '属性标识会统一为大写；已发布属性必须保留，可在新修订中停用。',
  metadataRequired: '必填属性',
  metadataArray: '数组',
  metadataDefault: '默认值',
  metadataArrayDefaultHint: '数组默认值使用 JSON 数组，例如 ["A","B"]。',
  metadataPrecision: '精度',
  metadataUnitDimension: '单位维度标识',
  metadataDefaultUnit: '默认单位标识',
  metadataUnitRevision: '单位修订',
  metadataUnitSource: '单位来源',
  metadataSourceTenant: '来源租户',
  metadataConstraintHint: '切换类型会清除不适用的约束，避免向服务端发送互斥字段。',
  metadataLimit: '一个 Schema 最多包含 200 个属性。',
  metadataDuplicate: '同一 Schema 内属性标识不能重复。',
  metadataDefaultInvalid: '默认值与属性类型或数组设置不匹配。',
  metadataConstraintInvalid: '属性约束范围不正确。',
  metadataDictionaryInvalid: '枚举字典或默认项不可用。',
  metadataUnitInvalid: '固定来源、单位修订或默认单位不可用。',
  metadataPublicationCheck: '发布校验',
  metadataTightened: '收紧约束',
  metadataRelaxed: '放宽约束',
  metadataIncompatible: '不兼容变更',
  metadataErrors: '校验错误',
  metadataPublishHint: '发布会替代同一作用域的当前修订；不兼容差异仅提示，不会自动迁移业务值。',
  metadataDisableHint: '停用后不再作为当前 Schema；租户定义停用后会回退到平台定义。',
  metadataRuntime: '运行时读取',
  metadataReadMode: '读取方式',
  metadataCurrent: '当前有效定义',
  metadataFixed: '固定来源与修订',
  metadataRuntimeHint: '当前读取仅返回启用属性；固定修订保留完整历史属性。',
  typeReferenceMetadata: '引用',
  stateMachineTitle: '状态机定义',
  stateMachineDescription:
    '维护版本化状态节点与确定性转换，并按显式来源和修订进行无副作用定义校验。',
  stateMachineCreate: '新建状态机',
  stateMachineEdit: '编辑状态机',
  stateMachineDetail: '状态机详情',
  stateMachineEmpty: '暂无状态机，可新建第一个租户定义。',
  stateMachineNodeCount: '节点数',
  stateMachineTransitionCount: '转换数',
  stateMachineNodes: '状态节点',
  stateMachineTransitions: '状态转换',
  stateMachineAddNode: '新增节点',
  stateMachineAddTransition: '新增转换',
  stateMachineInitial: '初始',
  stateMachineTerminal: '终态',
  stateMachineOutcome: '结果语义',
  stateMachineOutcomeNone: '无',
  stateMachineOutcomeSuccess: '成功',
  stateMachineOutcomeFailure: '失败',
  stateMachineOutcomeSkipped: '跳过',
  stateMachineColor: '颜色',
  stateMachineFrom: '来源状态',
  stateMachineTo: '目标状态',
  stateMachineActionNId: '动作标识',
  stateMachineActionName: '动作名称',
  stateMachineGraphHint:
    '节点标识在本修订内唯一；转换以“来源状态 + 动作标识”唯一，终态不得有出边。',
  stateMachineNodeLimit: '状态机必须包含 1～200 个节点。',
  stateMachineTransitionLimit: '状态机最多包含 1000 条转换。',
  stateMachineDuplicateNode: '节点标识不能重复。',
  stateMachineDuplicateTransition: '同一来源状态和动作只能指向一个目标。',
  stateMachineInitialInvalid: '发布图必须且只能有一个初始节点。',
  stateMachineUnreachable: '所有节点必须能从初始节点到达。',
  stateMachineTerminalOutgoing: '终态不能有出边。',
  stateMachineActionNameMismatch: '同一动作标识在本修订内必须使用相同名称。',
  stateMachineColorInvalid: '颜色必须为空或使用 #RRGGBB 格式。',
  stateMachineEndpointInvalid: '转换两端必须引用本修订中的节点。',
  stateMachineInvalid: '状态机节点、转换或图约束不符合要求。',
  stateMachinePublicationCheck: '发布校验',
  stateMachineAddedNodes: '新增节点',
  stateMachineRemovedNodes: '移除节点',
  stateMachineChangedNodes: '变更节点',
  stateMachineAddedTransitions: '新增转换',
  stateMachineRemovedTransitions: '移除转换',
  stateMachineChangedTransitions: '变更转换',
  stateMachinePublicationErrors: '发布错误',
  stateMachinePublishHint: '发布会原子冻结整份图并替代同一来源的当前修订；历史绑定不会迁移。',
  stateMachineDisableHint: '停用后不再供新业务选择；显式固定的历史修订仍可读取和校验。',
  stateMachineCheck: '定义校验',
  stateMachineCheckTitle: '状态转换定义校验',
  stateMachineAvailable: '可用定义',
  stateMachineReadMode: '读取方式',
  stateMachineCurrent: '当前版本',
  stateMachineFixed: '固定修订',
  stateMachineSource: '定义来源',
  stateMachineSourceTenant: '来源租户',
  stateMachineCheckFrom: '当前状态',
  stateMachineCheckAction: '动作标识',
  stateMachineAllowed: '定义允许',
  stateMachineDenied: '定义不允许',
  stateMachineCheckHint: '此校验仅判断定义路径，不执行动作，也不证明业务权限或前置条件。',
  stateMachineTarget: '目标状态',
  stateMachineReasonCode: '原因码',
}
export type ReferenceDataMessages = { [Key in keyof typeof referenceDataZh]: string }
export const referenceDataEn: ReferenceDataMessages = {
  section: 'Reference data',
  parameterTitle: 'Parameters',
  parameterDescription:
    'Manage configuration keys by domain. An active key stops inheritance, including empty values.',
  domains: 'Domains',
  newDomain: 'New domain',
  keys: 'Keys',
  newKey: 'Add key',
  newValue: 'Add value',
  selectDomain: 'Select a domain',
  domainLoading: 'Loading domain',
  keyCount: 'Keys',
  active: 'Active',
  enable: 'Enable',
  changeReason: 'Change reason',
  parameterStateHint:
    'State changes immediately affect effective configuration. Disabling restores fallback to the next scope.',
  dataType: 'Data type',
  valueMode: 'Value mode',
  singleValue: 'Single',
  multiValue: 'Multiple',
  value: 'Value',
  defaultValue: 'Default value',
  notConfigured: 'Not configured',
  mandatory: 'Required value',
  readOnlyKey: 'Read-only key',
  readOnlyHint: 'Only trusted synchronization or migration can change this key.',
  typeLocked:
    'This path has held a value. Its type and mode are fixed; create a new key to change them.',
  dictionaryNId: 'Published dictionary ID',
  referenceTarget: 'Reference target',
  fullPath: 'Full path',
  blocksInheritance: 'Stops inheritance',
  emptyValueHint:
    'An unset value uses its default. When both are unset, inheritance stops. Disable the key to restore fallback.',
  multiValueHint:
    'All enabled values are returned. Multiple defaults are allowed and must be enabled. Add values before marking a multi-value key as required.',
  isDefault: 'Default',
  history: 'Change history',
  historyBefore: 'Before summary',
  historyAfter: 'After summary',
  objectType: 'Object',
  changeType: 'Change',
  changedBy: 'Changed by',
  effective: 'Effective configuration',
  valueSource: 'Value source',
  usesDefault: 'Uses default',
  configuredValue: 'Uses configured value',
  viewEffective: 'View effective configuration',
  noKeys: 'This domain has no configuration keys.',
  keyLimit: 'A domain supports at most 500 keys.',
  multiLimit: 'A multi-value key supports at most 1,000 entries.',
  duplicateValue: 'Enabled values must be unique.',
  duplicateConfiguration: 'This business ID already exists.',
  mandatoryMissing: 'A required key needs a value, a default, or at least one enabled entry.',
  modeConflict: 'Single and multiple value contents cannot be mixed.',
  defaultMustBeEnabled: 'Default entries must be enabled. Clear the default flag first.',
  sensitiveRejected:
    'Parameters cannot store passwords, tokens, private keys, or connection strings containing credentials.',
  jsonInvalid: 'Enter a valid typed value. Use the unset control for an unconfigured value.',
  valueDetails: 'Value entries',
  decimalHint: 'Preserves decimal precision',
  typeString: 'String',
  typeInteger: 'Integer (Int64)',
  typeDecimal: 'Decimal',
  typeBoolean: 'Boolean',
  typeDate: 'Date',
  typeDateTime: 'Date and time (with offset)',
  typeEnum: 'Dictionary enum',
  typeJson: 'JSON data',
  typeReference: 'Opaque reference',
  trueValue: 'True',
  falseValue: 'False',
  noDomain: 'No domains yet. Create the first domain.',
  enumLoad: 'Load dictionary items',
  noValues: 'No value entries',
  parameterIdentityHint: 'Domain and key IDs cannot contain periods or be renamed after saving.',
  dictionaryTitle: 'Dictionaries',
  dictionaryDescription:
    'Maintain versioned dictionaries. Tenant dictionaries replace the complete platform dictionary. Published content is read-only.',
  create: 'New dictionary',
  edit: 'Edit',
  detail: 'Details',
  clone: 'Clone new revision',
  publish: 'Publish',
  disable: 'Disable',
  more: 'More',
  keyword: 'Keyword',
  name: 'Name',
  nId: 'Business ID',
  scope: 'Scope',
  status: 'Status',
  revision: 'Revision',
  enabledCount: 'Enabled items',
  updatedOn: 'Updated',
  publishedBy: 'Published by',
  description: 'Description',
  tenant: 'Tenant',
  platform: 'Platform',
  all: 'All',
  draft: 'Draft',
  published: 'Published',
  superseded: 'Superseded',
  disabled: 'Disabled',
  basics: 'Basic information',
  items: 'Dictionary items',
  addItem: 'Add item',
  enabled: 'Enabled',
  sort: 'Order',
  moveUp: 'Move up',
  moveDown: 'Move down',
  remove: 'Remove',
  save: 'Save',
  cancel: 'Cancel',
  close: 'Close',
  refresh: 'Refresh',
  required: 'This field is required',
  invalidNId: 'Invalid ID format',
  duplicateItem: 'Item IDs must be unique',
  invalidSort: 'Order must be a nonnegative integer',
  itemLimit: 'A dictionary supports at most 1,000 items',
  enabledRequired: 'At least one enabled item is required to publish',
  historyProtected: 'Historical items must be retained. Disable them and add a new ID.',
  readOnly: 'This revision is read-only. Clone a new draft to make changes.',
  protected: 'This record is frozen, locked, or you lack permission to manage this scope.',
  publicationTitle: 'Publication checks and changes',
  previousRevision: 'Previous published revision',
  firstPublication: 'First publication',
  added: 'Added items',
  changed: 'Changed items',
  disabledItems: 'Disabled items',
  validationPassed: 'Validation passed. Ready to publish.',
  noChanges: 'None',
  publicationHint:
    'Publishing replaces the current version in the same scope. Historical content is retained.',
  reason: 'Reason for disabling',
  disableHint:
    'The dictionary will no longer be current. Disabling a tenant dictionary restores the platform fallback.',
  conflict:
    'The record has changed. Your unsaved input is preserved. Copy it or reload before continuing.',
  reload: 'Reload',
  copyUnsaved: 'Copy unsaved input',
  copied: 'Unsaved input copied',
  discard: 'Discard unsaved changes?',
  saved: 'Saved',
  publishedSuccess: 'Published',
  disabledSuccess: 'Disabled',
  cloned: 'New draft created',
  unavailable: 'Reference data is temporarily unavailable. Try again later.',
  forbidden: 'You do not have permission for this action.',
  notFound: 'The record was not found or is not accessible.',
  invalid: 'Validation failed. Check the fields.',
  stateInvalid: 'The current state does not allow this action.',
  traceId: 'Trace ID',
  empty: 'No dictionaries yet. Create the first dictionary.',
  loading: 'Loading dictionaries',
  itemIdentityHint:
    'IDs are normalized to uppercase. Disable published items instead of deleting or renaming them.',
  formTitle: 'Dictionary',
  copyFailed: 'Copy failed. Keep your input manually.',
  dynamicTitle: 'Dynamic properties',
  dynamicDescription:
    'Maintain versioned dynamic definitions, fields, and records. Tenant revisions replace the complete platform revision.',
  dynamicCreate: 'New dynamic configuration',
  dynamicSelect: 'Select a dynamic configuration',
  dynamicLoading: 'Loading dynamic configurations',
  dynamicEmpty: 'No dynamic configurations yet. Create the first definition.',
  dynamicFields: 'Field definitions',
  dynamicRecords: 'Configuration records',
  dynamicPublication: 'Publication check',
  dynamicFieldCount: 'Fields',
  dynamicRecordCount: 'Records',
  dynamicValueCount: 'Values',
  publishedOn: 'Published',
  dynamicEditDefinition: 'Edit definition',
  dynamicAddField: 'Add field',
  dynamicEditField: 'Edit field',
  dynamicAddRecord: 'Add record',
  dynamicEditRecord: 'Edit record',
  dynamicPublicationCheck: 'Publication check',
  dynamicDefinitionDetails: 'Dynamic configuration',
  dynamicFieldDetails: 'Field details',
  dynamicRecordDetails: 'Record details',
  dynamicRequired: 'Required field',
  dynamicCategory: 'Category',
  dynamicValues: 'Field values',
  dynamicMinLength: 'Minimum length',
  dynamicMaxLength: 'Maximum length',
  dynamicMinValue: 'Minimum value',
  dynamicMaxValue: 'Maximum value',
  dynamicScale: 'Scale',
  dynamicPattern: 'Pattern',
  dynamicNoFields: 'This definition has no fields.',
  dynamicFieldIdentityHint:
    'Field IDs cannot be renamed after saving. Retain and disable fields that have values or were published.',
  dynamicReplacementHint:
    'A tenant dynamic configuration replaces the complete platform configuration; records are not merged.',
  dynamicRemoveFieldHint: 'Remove this unused and unpublished field?',
  dynamicDisableRecordHint: 'The record will be excluded from runtime results. Enter a reason.',
  dynamicInvalid: 'A dynamic field definition or record value does not satisfy its constraints.',
  dynamicLimit: 'The dynamic configuration exceeds its field, record, or value limit.',
  dynamicEnumInvalid: 'Enum values must come from a published dictionary in the same scope.',
  dynamicConstraintInvalid: 'The constraint range is invalid.',
  unitTitle: 'Units of measure',
  unitDescription:
    'Maintain versioned dimensions and base conversions, then calculate with an explicit source and revision.',
  unitCreate: 'New dimension',
  unitEdit: 'Edit dimension',
  unitDetail: 'Dimension details',
  unitEmpty: 'No unit dimensions yet. Create the first tenant dimension.',
  unitConversionKind: 'Conversion kind',
  unitRatio: 'Ratio',
  unitAbsoluteTemperature: 'Absolute temperature',
  unitBase: 'Base unit',
  unitCount: 'Units',
  unitDefinitions: 'Unit definitions',
  unitAdd: 'Add unit',
  unitNoDefinitions: 'Add at least one unit and choose the base unit.',
  unitNId: 'Unit ID',
  unitName: 'Unit name',
  unitSymbol: 'Symbol',
  unitFactor: 'Factor to base',
  unitOffset: 'Offset to base',
  unitDecimalPlaces: 'Decimal places',
  unitRoundingMode: 'Rounding mode',
  unitToEven: 'To even',
  unitAwayFromZero: 'Away from zero',
  unitSystemDefined: 'System defined',
  unitSystemReadOnly:
    'Versioned seeds maintain this system dimension. Every field is read-only through the management API.',
  unitLimit: 'A dimension must contain between 1 and 200 units.',
  unitDuplicate: 'Unit IDs must be unique within a dimension.',
  unitFactorInvalid: 'The factor must be a decimal string greater than zero.',
  unitDecimalInvalid: 'Enter a decimal string without exponent notation.',
  unitRatioOffset: 'Ratio conversions require an offset of zero.',
  unitDecimalPlacesInvalid: 'Decimal places must be an integer from 0 to 12.',
  unitBaseInvalid: 'The base unit must exist and be enabled with factor 1 and offset 0.',
  unitDecimalHint: 'Quantities, factors, offsets, and results stay as decimal strings.',
  unitInvalid: 'The dimension, unit, or conversion parameters violate their constraints.',
  unitOverflow: 'The conversion result exceeds the supported numeric range.',
  unitPublishHint:
    'Publishing atomically freezes this complete unit revision and replaces the current revision in the same source.',
  unitDisableHint:
    'The dimension will no longer be available for new selections. Fixed historical revisions remain readable.',
  unitTryConvert: 'Try conversion',
  unitConvertTitle: 'Unit conversion',
  unitConvert: 'Convert',
  unitFrom: 'From unit',
  unitTo: 'To unit',
  unitReadMode: 'Read mode',
  unitFixedRevision: 'Fixed revision',
  unitCurrentRevision: 'Current revision',
  unitWasRounded: 'Rounded',
  metadataTitle: 'Metadata schemas',
  metadataDescription:
    'Manage versioned entity schemas and attribute constraints, then read the current effective definition or an explicit source and revision.',
  metadataCreate: 'New schema',
  metadataEdit: 'Edit schema',
  metadataDetail: 'Schema details',
  metadataEmpty: 'No metadata schemas yet. Create the first tenant definition.',
  metadataAttributeCount: 'Attributes',
  metadataAttributes: 'Attribute definitions',
  metadataAddAttribute: 'Add attribute',
  metadataNoAttributes: 'Add at least one enabled attribute before publishing.',
  metadataAttributeIdentityHint:
    'Attribute IDs are normalized to uppercase. Published attributes must be retained and may be disabled in a new revision.',
  metadataRequired: 'Required attribute',
  metadataArray: 'Array',
  metadataDefault: 'Default value',
  metadataArrayDefaultHint: 'Array defaults use a JSON array, for example ["A","B"].',
  metadataPrecision: 'Precision',
  metadataUnitDimension: 'Unit dimension ID',
  metadataDefaultUnit: 'Default unit ID',
  metadataUnitRevision: 'Unit revision',
  metadataUnitSource: 'Unit source',
  metadataSourceTenant: 'Source tenant',
  metadataConstraintHint:
    'Changing the type clears constraints that do not apply, so mutually exclusive fields are never sent.',
  metadataLimit: 'A schema supports at most 200 attributes.',
  metadataDuplicate: 'Attribute IDs must be unique within a schema.',
  metadataDefaultInvalid: 'The default value does not match the attribute type or array setting.',
  metadataConstraintInvalid: 'The attribute constraints are invalid.',
  metadataDictionaryInvalid: 'The enum dictionary or default item is unavailable.',
  metadataUnitInvalid: 'The fixed source, unit revision, or default unit is unavailable.',
  metadataPublicationCheck: 'Publication check',
  metadataTightened: 'Tightened constraints',
  metadataRelaxed: 'Relaxed constraints',
  metadataIncompatible: 'Incompatible changes',
  metadataErrors: 'Validation errors',
  metadataPublishHint:
    'Publishing replaces the current revision in this scope. Incompatible changes are reported and do not migrate business values.',
  metadataDisableHint:
    'The schema will no longer be current. Disabling a tenant schema restores the platform fallback.',
  metadataRuntime: 'Runtime read',
  metadataReadMode: 'Read mode',
  metadataCurrent: 'Current effective definition',
  metadataFixed: 'Fixed source and revision',
  metadataRuntimeHint:
    'Current reads contain enabled attributes only. Fixed revisions retain the complete attribute history.',
  typeReferenceMetadata: 'Reference',
  stateMachineTitle: 'State machines',
  stateMachineDescription:
    'Manage versioned state nodes and deterministic transitions, then validate a definition with an explicit source and revision.',
  stateMachineCreate: 'New state machine',
  stateMachineEdit: 'Edit state machine',
  stateMachineDetail: 'State machine details',
  stateMachineEmpty: 'No state machines yet. Create the first tenant definition.',
  stateMachineNodeCount: 'Nodes',
  stateMachineTransitionCount: 'Transitions',
  stateMachineNodes: 'State nodes',
  stateMachineTransitions: 'State transitions',
  stateMachineAddNode: 'Add node',
  stateMachineAddTransition: 'Add transition',
  stateMachineInitial: 'Initial',
  stateMachineTerminal: 'Terminal',
  stateMachineOutcome: 'Outcome',
  stateMachineOutcomeNone: 'None',
  stateMachineOutcomeSuccess: 'Success',
  stateMachineOutcomeFailure: 'Failure',
  stateMachineOutcomeSkipped: 'Skipped',
  stateMachineColor: 'Color',
  stateMachineFrom: 'From state',
  stateMachineTo: 'To state',
  stateMachineActionNId: 'Action ID',
  stateMachineActionName: 'Action name',
  stateMachineGraphHint:
    'Node IDs are unique within a revision. A transition is unique by from-state and action; terminal nodes have no outgoing transitions.',
  stateMachineNodeLimit: 'A state machine must contain 1 to 200 nodes.',
  stateMachineTransitionLimit: 'A state machine supports at most 1,000 transitions.',
  stateMachineDuplicateNode: 'Node IDs must be unique.',
  stateMachineDuplicateTransition: 'One action from a state can have only one target.',
  stateMachineInitialInvalid: 'A publishable graph must have exactly one initial node.',
  stateMachineUnreachable: 'Every node must be reachable from the initial node.',
  stateMachineTerminalOutgoing: 'Terminal nodes cannot have outgoing transitions.',
  stateMachineActionNameMismatch: 'One action ID must use the same display name in this revision.',
  stateMachineColorInvalid: 'Color must be empty or use #RRGGBB.',
  stateMachineEndpointInvalid: 'Both transition endpoints must belong to this revision.',
  stateMachineInvalid: 'The state machine nodes, transitions, or graph constraints are invalid.',
  stateMachinePublicationCheck: 'Publication check',
  stateMachineAddedNodes: 'Added nodes',
  stateMachineRemovedNodes: 'Removed nodes',
  stateMachineChangedNodes: 'Changed nodes',
  stateMachineAddedTransitions: 'Added transitions',
  stateMachineRemovedTransitions: 'Removed transitions',
  stateMachineChangedTransitions: 'Changed transitions',
  stateMachinePublicationErrors: 'Publication errors',
  stateMachinePublishHint:
    'Publishing atomically freezes the complete graph and replaces the current revision in this source. Historical bindings are not migrated.',
  stateMachineDisableHint:
    'The definition will no longer be available for new selections. Explicit fixed historical revisions remain readable.',
  stateMachineCheck: 'Definition check',
  stateMachineCheckTitle: 'State transition definition check',
  stateMachineAvailable: 'Available definition',
  stateMachineReadMode: 'Read mode',
  stateMachineCurrent: 'Current revision',
  stateMachineFixed: 'Fixed revision',
  stateMachineSource: 'Definition source',
  stateMachineSourceTenant: 'Source tenant',
  stateMachineCheckFrom: 'Current state',
  stateMachineCheckAction: 'Action ID',
  stateMachineAllowed: 'Allowed by definition',
  stateMachineDenied: 'Not allowed',
  stateMachineCheckHint:
    'This check only evaluates the definition path. It does not execute an action or prove business permission or preconditions.',
  stateMachineTarget: 'Target state',
  stateMachineReasonCode: 'Reason code',
}
