using IndustrialPlatform.SystemData.Domain.DatabaseOrchestration;
using IndustrialPlatform.SystemData.Infrastructure.Persistence.Entities;

namespace IndustrialPlatform.SystemData.Infrastructure.Persistence;

/// <summary>
/// POCO ↔ 聚合双向映射助手,集中承载 snake_case 物理列与领域类型的转换。
/// 持久化层专用(internal);领域不变量仍由聚合构造与业务方法维护,重建构造不重新校验。
/// 父子聚合(Plan/Operation)的子步骤由仓储单独装载/插入,不在本映射内。
/// </summary>
internal static class TableMapper
{
    // ===== 环境策略 =====

    public static DatabaseEnvironmentPolicyTable ToTable(DatabaseEnvironmentPolicy policy) => new()
    {
        Id = policy.Id,
        IsFrozen = policy.IsFrozen,
        IsLocked = policy.IsLocked,
        IsDeleted = policy.IsDeleted,
        EntityType = policy.EntityType,
        CreatedOn = policy.CreatedOn,
        LastUpdatedOn = policy.LastUpdatedOn,
        OptimisticVersion = policy.OptimisticVersion,
        ConcurrencyVersion = policy.ConcurrencyVersion,
        TenantNId = policy.TenantNId,
        EnvironmentNId = policy.EnvironmentNId,
        EnvironmentKind = policy.EnvironmentKind,
        ApprovalRequired = policy.ApprovalRequired,
        BackupRequired = policy.BackupRequired,
        PlanTtlSeconds = policy.PlanTtlSeconds,
        PlanTimeoutSeconds = policy.PlanTimeoutSeconds,
        ApplyTimeoutSeconds = policy.ApplyTimeoutSeconds,
        MaxPreMigrationRetries = policy.MaxPreMigrationRetries,
        PolicyRevision = policy.PolicyRevision,
    };

    public static DatabaseEnvironmentPolicy ToEnvironmentPolicy(DatabaseEnvironmentPolicyTable row) => new(
        row.Id,
        row.TenantNId,
        row.EnvironmentNId,
        row.EnvironmentKind,
        row.ApprovalRequired,
        row.BackupRequired,
        row.PlanTtlSeconds,
        row.PlanTimeoutSeconds,
        row.ApplyTimeoutSeconds,
        row.MaxPreMigrationRetries,
        row.PolicyRevision,
        row.IsFrozen,
        row.IsLocked,
        row.IsDeleted,
        row.EntityType,
        row.CreatedOn,
        row.LastUpdatedOn,
        row.OptimisticVersion,
        row.ConcurrencyVersion);

    // ===== 注册清单 =====

    public static DatabaseRegistrationTable ToTable(DatabaseRegistration registration) => new()
    {
        Id = registration.Id,
        IsFrozen = registration.IsFrozen,
        IsLocked = registration.IsLocked,
        IsDeleted = registration.IsDeleted,
        EntityType = registration.EntityType,
        CreatedOn = registration.CreatedOn,
        LastUpdatedOn = registration.LastUpdatedOn,
        OptimisticVersion = registration.OptimisticVersion,
        ConcurrencyVersion = registration.ConcurrencyVersion,
        TenantNId = registration.TenantNId,
        EnvironmentNId = registration.EnvironmentNId,
        ServiceKey = registration.ServiceKey,
        Provider = registration.Provider,
        LogicalDatabaseName = registration.LogicalDatabaseName,
        PhysicalDatabaseName = registration.PhysicalDatabaseName,
        IsSharedPhysicalDatabase = registration.IsSharedPhysicalDatabase,
        TopologyMode = registration.TopologyMode,
        TopologyRevision = registration.TopologyRevision,
        MigrationArtifactId = registration.MigrationArtifactId,
        MigrationVersion = registration.MigrationVersion,
        ArtifactChecksum = registration.ArtifactChecksum,
        ArtifactSignature = registration.ArtifactSignature,
        OwnerNId = registration.OwnerNId,
        DesiredState = registration.DesiredState,
        AutoProvision = registration.AutoProvision,
        AutoMigrate = registration.AutoMigrate,
        ManifestVersion = registration.ManifestVersion,
        ManifestChecksum = registration.ManifestChecksum,
        Status = registration.Status,
    };

    public static DatabaseRegistration ToRegistration(DatabaseRegistrationTable row) => new(
        row.Id,
        row.TenantNId,
        row.EnvironmentNId,
        row.ServiceKey,
        row.Provider,
        row.LogicalDatabaseName,
        row.PhysicalDatabaseName,
        row.IsSharedPhysicalDatabase,
        row.TopologyMode,
        row.TopologyRevision,
        row.MigrationArtifactId,
        row.MigrationVersion,
        row.ArtifactChecksum,
        row.ArtifactSignature,
        row.OwnerNId,
        row.DesiredState,
        row.AutoProvision,
        row.AutoMigrate,
        row.ManifestVersion,
        row.ManifestChecksum,
        row.Status,
        row.IsFrozen,
        row.IsLocked,
        row.IsDeleted,
        row.EntityType,
        row.CreatedOn,
        row.LastUpdatedOn,
        row.OptimisticVersion,
        row.ConcurrencyVersion);

    // ===== 不可变计划 =====

    public static DatabaseProvisionPlanTable ToTable(DatabaseProvisionPlan plan) => new()
    {
        Id = plan.Id,
        IsFrozen = plan.IsFrozen,
        IsLocked = plan.IsLocked,
        IsDeleted = plan.IsDeleted,
        EntityType = plan.EntityType,
        CreatedOn = plan.CreatedOn,
        LastUpdatedOn = plan.LastUpdatedOn,
        OptimisticVersion = plan.OptimisticVersion,
        ConcurrencyVersion = plan.ConcurrencyVersion,
        TenantNId = plan.TenantNId,
        PlanNId = plan.PlanNId,
        EnvironmentNId = plan.EnvironmentNId,
        ServiceKey = plan.ServiceKey,
        RequestedMigrationVersion = plan.RequestedMigrationVersion,
        CurrentMigrationVersion = plan.CurrentMigrationVersion,
        TargetStateFingerprint = plan.TargetStateFingerprint,
        PlanChecksum = plan.PlanChecksum,
        RiskLevel = plan.RiskLevel,
        DestructiveChangeDetected = plan.DestructiveChangeDetected,
        RequiredPolicies = plan.RequiredPolicies,
        ExpiresOn = plan.ExpiresOn,
        CreatedByUserNId = plan.CreatedByUserNId,
    };

    public static DatabaseProvisionPlan ToPlan(
        DatabaseProvisionPlanTable row,
        IReadOnlyCollection<DatabasePlanStep> steps) => new(
        row.Id,
        row.TenantNId,
        row.PlanNId,
        row.EnvironmentNId,
        row.ServiceKey,
        row.RequestedMigrationVersion,
        row.CurrentMigrationVersion,
        row.TargetStateFingerprint,
        row.PlanChecksum,
        row.RiskLevel,
        row.DestructiveChangeDetected,
        row.RequiredPolicies,
        row.ExpiresOn,
        row.CreatedByUserNId,
        steps,
        row.IsFrozen,
        row.IsLocked,
        row.IsDeleted,
        row.EntityType,
        row.CreatedOn,
        row.LastUpdatedOn,
        row.OptimisticVersion,
        row.ConcurrencyVersion);

    public static DatabasePlanStepTable ToTable(DatabasePlanStep step, Guid planId, bool planIsDeleted) => new()
    {
        Id = step.Id,
        IsFrozen = step.IsFrozen,
        IsLocked = step.IsLocked,
        IsDeleted = step.IsDeleted,
        EntityType = step.EntityType,
        CreatedOn = step.CreatedOn,
        LastUpdatedOn = step.LastUpdatedOn,
        OptimisticVersion = step.OptimisticVersion,
        ConcurrencyVersion = step.ConcurrencyVersion,
        PlanId = planId,
        PlanIsDeleted = planIsDeleted,
        Sequence = step.Sequence,
        StepKind = step.StepKind,
        InputSummary = step.InputSummary,
        PreconditionSummary = step.PreconditionSummary,
        PostconditionSummary = step.PostconditionSummary,
        RiskLevel = step.RiskLevel,
    };

    public static DatabasePlanStep ToPlanStep(DatabasePlanStepTable row) => new(
        row.Id,
        row.Sequence,
        row.StepKind,
        row.InputSummary,
        row.PreconditionSummary,
        row.PostconditionSummary,
        row.RiskLevel,
        row.IsFrozen,
        row.IsLocked,
        row.IsDeleted,
        row.EntityType,
        row.CreatedOn,
        row.LastUpdatedOn,
        row.OptimisticVersion,
        row.ConcurrencyVersion);

    // ===== 审批 =====

    public static DatabaseApprovalTable ToTable(DatabaseApproval approval) => new()
    {
        Id = approval.Id,
        IsFrozen = approval.IsFrozen,
        IsLocked = approval.IsLocked,
        IsDeleted = approval.IsDeleted,
        EntityType = approval.EntityType,
        CreatedOn = approval.CreatedOn,
        LastUpdatedOn = approval.LastUpdatedOn,
        OptimisticVersion = approval.OptimisticVersion,
        ConcurrencyVersion = approval.ConcurrencyVersion,
        TenantNId = approval.TenantNId,
        ApprovalNId = approval.ApprovalNId,
        PlanNId = approval.PlanNId,
        PlanChecksum = approval.PlanChecksum,
        TargetStateFingerprint = approval.TargetStateFingerprint,
        ApprovedByUserNId = approval.ApprovedByUserNId,
        Reason = approval.Reason,
        ApprovedOn = approval.ApprovedOn,
        ExpiresOn = approval.ExpiresOn,
        Status = approval.Status,
    };

    public static DatabaseApproval ToApproval(DatabaseApprovalTable row) => new(
        row.Id,
        row.TenantNId,
        row.ApprovalNId,
        row.PlanNId,
        row.PlanChecksum,
        row.TargetStateFingerprint,
        row.ApprovedByUserNId,
        row.Reason,
        row.ApprovedOn,
        row.ExpiresOn,
        row.Status,
        row.IsFrozen,
        row.IsLocked,
        row.IsDeleted,
        row.EntityType,
        row.CreatedOn,
        row.LastUpdatedOn,
        row.OptimisticVersion,
        row.ConcurrencyVersion);

    // ===== 备份证据 =====

    public static DatabaseBackupEvidenceTable ToTable(DatabaseBackupEvidence evidence) => new()
    {
        Id = evidence.Id,
        IsFrozen = evidence.IsFrozen,
        IsLocked = evidence.IsLocked,
        IsDeleted = evidence.IsDeleted,
        EntityType = evidence.EntityType,
        CreatedOn = evidence.CreatedOn,
        LastUpdatedOn = evidence.LastUpdatedOn,
        OptimisticVersion = evidence.OptimisticVersion,
        ConcurrencyVersion = evidence.ConcurrencyVersion,
        TenantNId = evidence.TenantNId,
        EvidenceNId = evidence.EvidenceNId,
        PlanNId = evidence.PlanNId,
        PlanChecksum = evidence.PlanChecksum,
        TargetStateFingerprint = evidence.TargetStateFingerprint,
        BackupProvider = evidence.BackupProvider,
        BackupReference = evidence.BackupReference,
        CapturedOn = evidence.CapturedOn,
        VerifiedOn = evidence.VerifiedOn,
        RetentionUntil = evidence.RetentionUntil,
        VerifiedByUserNId = evidence.VerifiedByUserNId,
        Status = evidence.Status,
    };

    public static DatabaseBackupEvidence ToBackupEvidence(DatabaseBackupEvidenceTable row) => new(
        row.Id,
        row.TenantNId,
        row.EvidenceNId,
        row.PlanNId,
        row.PlanChecksum,
        row.TargetStateFingerprint,
        row.BackupProvider,
        row.BackupReference,
        row.CapturedOn,
        row.VerifiedOn,
        row.RetentionUntil,
        row.VerifiedByUserNId,
        row.Status,
        row.IsFrozen,
        row.IsLocked,
        row.IsDeleted,
        row.EntityType,
        row.CreatedOn,
        row.LastUpdatedOn,
        row.OptimisticVersion,
        row.ConcurrencyVersion);

    // ===== Operation =====

    public static DatabaseProvisionOperationTable ToTable(DatabaseProvisionOperation operation) => new()
    {
        Id = operation.Id,
        IsFrozen = operation.IsFrozen,
        IsLocked = operation.IsLocked,
        IsDeleted = operation.IsDeleted,
        EntityType = operation.EntityType,
        CreatedOn = operation.CreatedOn,
        LastUpdatedOn = operation.LastUpdatedOn,
        OptimisticVersion = operation.OptimisticVersion,
        ConcurrencyVersion = operation.ConcurrencyVersion,
        TenantNId = operation.TenantNId,
        OperationNId = operation.OperationNId,
        Kind = operation.Kind,
        EnvironmentNId = operation.EnvironmentNId,
        ServiceKey = operation.ServiceKey,
        PlanNId = operation.PlanNId,
        RequestedVersion = operation.RequestedVersion,
        IdempotencyKey = operation.IdempotencyKey,
        RequestHash = operation.RequestHash,
        Status = operation.Status,
        Phase = operation.Phase,
        Attempt = operation.Attempt,
        LeaseOwner = operation.LeaseOwner,
        LeaseExpiresOn = operation.LeaseExpiresOn,
        HeartbeatOn = operation.HeartbeatOn,
        QueuedOn = operation.QueuedOn,
        StartedOn = operation.StartedOn,
        CompletedOn = operation.CompletedOn,
        TimeoutOn = operation.TimeoutOn,
        SanitizedErrorCode = operation.SanitizedErrorCode,
        SanitizedErrorSummary = operation.SanitizedErrorSummary,
        TraceId = operation.TraceId,
        CreatedByUserNId = operation.CreatedByUserNId,
    };

    public static DatabaseProvisionOperation ToOperation(
        DatabaseProvisionOperationTable row,
        IReadOnlyCollection<DatabaseOperationStep> steps) => new(
        row.Id,
        row.TenantNId,
        row.OperationNId,
        row.Kind,
        row.EnvironmentNId,
        row.ServiceKey,
        row.PlanNId,
        row.RequestedVersion,
        row.IdempotencyKey,
        row.RequestHash,
        row.Status,
        row.Phase,
        row.Attempt,
        row.LeaseOwner,
        row.LeaseExpiresOn,
        row.HeartbeatOn,
        row.QueuedOn,
        row.StartedOn,
        row.CompletedOn,
        row.TimeoutOn,
        row.SanitizedErrorCode,
        row.SanitizedErrorSummary,
        row.TraceId,
        row.CreatedByUserNId,
        steps,
        row.IsFrozen,
        row.IsLocked,
        row.IsDeleted,
        row.EntityType,
        row.CreatedOn,
        row.LastUpdatedOn,
        row.OptimisticVersion,
        row.ConcurrencyVersion);

    public static DatabaseOperationStepTable ToTable(DatabaseOperationStep step, Guid operationId, bool operationIsDeleted) => new()
    {
        Id = step.Id,
        IsFrozen = step.IsFrozen,
        IsLocked = step.IsLocked,
        IsDeleted = step.IsDeleted,
        EntityType = step.EntityType,
        CreatedOn = step.CreatedOn,
        LastUpdatedOn = step.LastUpdatedOn,
        OptimisticVersion = step.OptimisticVersion,
        ConcurrencyVersion = step.ConcurrencyVersion,
        OperationId = operationId,
        OperationIsDeleted = operationIsDeleted,
        Sequence = step.Sequence,
        Phase = step.Phase,
        Attempt = step.Attempt,
        Status = step.Status,
        StartedOn = step.StartedOn,
        CompletedOn = step.CompletedOn,
        SanitizedErrorCode = step.SanitizedErrorCode,
        SanitizedErrorSummary = step.SanitizedErrorSummary,
    };

    public static DatabaseOperationStep ToOperationStep(DatabaseOperationStepTable row) => new(
        row.Id,
        row.Sequence,
        row.Phase,
        row.Attempt,
        row.Status,
        row.StartedOn,
        row.CompletedOn,
        row.SanitizedErrorCode,
        row.SanitizedErrorSummary,
        row.IsFrozen,
        row.IsLocked,
        row.IsDeleted,
        row.EntityType,
        row.CreatedOn,
        row.LastUpdatedOn,
        row.OptimisticVersion,
        row.ConcurrencyVersion);

    // ===== 迁移观察 =====

    public static DatabaseMigrationObservationTable ToTable(DatabaseMigrationObservation observation) => new()
    {
        Id = observation.Id,
        IsFrozen = observation.IsFrozen,
        IsLocked = observation.IsLocked,
        IsDeleted = observation.IsDeleted,
        EntityType = observation.EntityType,
        CreatedOn = observation.CreatedOn,
        LastUpdatedOn = observation.LastUpdatedOn,
        OptimisticVersion = observation.OptimisticVersion,
        ConcurrencyVersion = observation.ConcurrencyVersion,
        TenantNId = observation.TenantNId,
        EnvironmentNId = observation.EnvironmentNId,
        ServiceKey = observation.ServiceKey,
        DatabaseIdentityFingerprint = observation.DatabaseIdentityFingerprint,
        ObservedVersion = observation.ObservedVersion,
        ArtifactChecksum = observation.ArtifactChecksum,
        ObservedOn = observation.ObservedOn,
        OperationNId = observation.OperationNId,
        VerificationStatus = observation.VerificationStatus,
    };

    public static DatabaseMigrationObservation ToObservation(DatabaseMigrationObservationTable row) => new(
        row.Id,
        row.TenantNId,
        row.EnvironmentNId,
        row.ServiceKey,
        row.DatabaseIdentityFingerprint,
        row.ObservedVersion,
        row.ArtifactChecksum,
        row.ObservedOn,
        row.OperationNId,
        row.VerificationStatus,
        row.IsFrozen,
        row.IsLocked,
        row.IsDeleted,
        row.EntityType,
        row.CreatedOn,
        row.LastUpdatedOn,
        row.OptimisticVersion,
        row.ConcurrencyVersion);
}
