<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" />
    <ProjectReference Include="..\IndustrialPlatform.Identity.Application\IndustrialPlatform.Identity.Application.csproj" />
    <ProjectReference Include="..\IndustrialPlatform.Identity.Domain\IndustrialPlatform.Identity.Domain.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\IndustrialPlatform.Infrastructure\IndustrialPlatform.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\IndustrialPlatform.Logging\IndustrialPlatform.Logging.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\IndustrialPlatform.Security\IndustrialPlatform.Security.csproj" />
  </ItemGroup>

</Project>
