<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Npgsql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\backend\src\Services\SystemData\IndustrialPlatform.SystemData.Application\IndustrialPlatform.SystemData.Application.csproj" />
    <ProjectReference Include="..\..\..\src\backend\src\Services\SystemData\IndustrialPlatform.SystemData.Contracts\IndustrialPlatform.SystemData.Contracts.csproj" />
    <ProjectReference Include="..\..\..\src\backend\src\Services\SystemData\IndustrialPlatform.SystemData.Domain\IndustrialPlatform.SystemData.Domain.csproj" />
    <ProjectReference Include="..\..\..\src\backend\src\Services\SystemData\IndustrialPlatform.SystemData.Infrastructure\IndustrialPlatform.SystemData.Infrastructure.csproj" />
  </ItemGroup>

</Project>
